# Generated by Django 2.2.4 on 2019-09-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Board')),
            ],
        ),
        migrations.RenameField(
            model_name='paper',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='paper',
            name='date_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='subject',
            field=models.ManyToManyField(to='teacher.Subject'),
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Level')),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ManyToManyField(to='teacher.Chapter'),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='teacher.SchoolClass'),
            preserve_default=False,
        ),
    ]
