# Generated by Django 2.2.4 on 2019-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20190901_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='status',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='PaperStatus',
        ),
    ]
