# Generated by Django 2.2.4 on 2019-09-03 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190903_2142'),
        ('teacher', '0003_auto_20190901_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='chapter',
            new_name='chapters',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='grade',
            new_name='school_class',
        ),
        migrations.RemoveField(
            model_name='question',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='paper',
            name='questions',
            field=models.ManyToManyField(to='teacher.Question'),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.SmallIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Term'),
        ),
    ]
