# Generated by Django 2.2.4 on 2019-09-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_question_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='file_path',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
