# Generated by Django 2.2.4 on 2019-09-25 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_question_file_path'),
        ('user', '0002_auto_20190903_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.Paper'),
        ),
    ]
